#!/bin/bash

# *** LOAD ********************************************************************

# Load the default .bash_profile
[[ -s "${HOME}/.bash_profile" ]] && source "${HOME}/.bash_profile"


[ -f ~/.fzf.bash ] && source ~/.fzf.bash
