#!/bin/bash

# *** LOAD ********************************************************************

# Load the default .bash_profile
[[ -s "${HOME}/.bash_profile" ]] && source "${HOME}/.bash_profile"


[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Load Tilix 
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
    [[ -f "/etc/profile.d/vte.sh" ]] && source /etc/profile.d/vte.sh
fi

export NVM_DIR="$HOME/.nvm"
# These scripts pre-pend to path
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
